// ═══════════════════════════════════════════════════════════════
//  Zakaa Brand — Frontend Configuration File
//  Edit this file to update pricing, currency, and product catalog
// ═══════════════════════════════════════════════════════════════

// ─── Currency Settings ───────────────────────────────────────
// Update this value whenever the USD → EGP exchange rate changes.
// All EGP prices on the site are calculated from this rate automatically
// IF a product's "priceEGP" is set to null (auto-calculate mode).
const DOLLAR_RATE = 53; // 1 USD = 50 EGP  ← change this as needed

// ─── Site Settings ───────────────────────────────────────────
const SITE_CONFIG = {
  siteName: "Zakaa Brand",
  currency: {
    usdSymbol: "$",
    egpSymbol: "ج.م",
    dollarRate: DOLLAR_RATE, // referenced from above
  },
  whatsappNumber: "+20 1200653165", // used for order/inquiry links
  showOutOfStock: false,           // hide products with inStock: false
};

// ─── Product Catalog (JSON Schema) ───────────────────────────
//
// SCHEMA REFERENCE FOR EACH PRODUCT:
// {
//   id:           (string)  unique identifier, e.g. "product-001"
//   name:         (string)  display name of the product
//   category:     (string)  category label shown on the card
//   imagePath:    (string)  path to the product image, relative to index.html
//   priceUSD:     (number)  price in US dollars
//   priceEGP:     (number|null) price in EGP — set to null to auto-calculate
//                            from priceUSD × DOLLAR_RATE
//   description:  (string)  full description shown when expanded
//   ageMin:       (number)  minimum recommended age (e.g. 4)
//   ageLabel:     (string)  display label (e.g. "Ages 4+")
//   badge:        ("new" | "popular" | null)  badge shown on the card image
//   inStock:      (boolean) whether the item is available
//   skills:       (string[]) list of skills/benefits this game develops
//   players:      (string)  e.g. "2–4 players"
//   playTime:     (string)  e.g. "20–40 min"
// }
//
// TO ADD A NEW PRODUCT: copy one block below, paste it at the end of
// the array (before the closing ]), fill in the fields, save the file.
// The website will automatically render the new card.

const PRODUCTS = [
  {
    id: "product-001",
    name: "Puzzle Pyramid",
    category: "Logic & Puzzles",
    imagePath: "images/photo_2_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 190,
    description: "A layered pyramid puzzle that challenges spatial reasoning and hand-eye coordination. Each tier introduces a new colour sequence, pushing children to plan ahead and think logically as they build upward.",
    ageMin: 4,
    ageLabel: "Ages 4+",
    badge: "new",
    inStock: true,
    skills: ["Spatial Reasoning", "Problem Solving", "sFine Motor Skills"],
    players: "1 players",
    playTime: "15–30 min",
  },
  {
    id: "product-002",
    name: "Color & Shape Match",
    category: "Visual Learning",
    imagePath: "images/photo_3_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Bright, tactile tiles that invite young learners to sort, match, and pattern by colour and shape. Perfect for building early maths foundations while keeping toddlers fully engaged.",
    ageMin: 3,
    ageLabel: "Ages 3+",
    badge: "popular",
    inStock: false,
    skills: ["Colour Recognition", "Pattern Thinking", "Visual Acuity"],
    players: "1 players",
    playTime: "10–20 min",
  },
  {
    id: "product-003",
    name: "Memory Tower",
    category: "Memory & Focus",
    imagePath: "images/photo_5_2026-03-21_16-00-02.jpg",
    priceUSD: 2.08,
    priceEGP: 110,
    description: "Stack the rings in the correct order from memory alone. Each round the sequence grows longer, training working memory and concentration in a wonderfully frustrating race to the top.",
    ageMin: 5,
    ageLabel: "Ages 5+",
    badge: null,
    inStock: true,
    skills: ["Working Memory", "Concentration", "Sequencing"],
    players: "1–3 players",
    playTime: "20–35 min",
  },
  {
    id: "product-004",
    name: "Number Quest",
    category: "Math & Numbers",
    imagePath: "images/photo_6_2026-03-21_16-00-02.jpg",
    priceUSD: 2.45,
    priceEGP: 130,
    description: "An adventure board game where every move requires quick arithmetic. Children solve addition, subtraction, and simple multiplication challenges to advance through enchanted lands — learning maths without even realising it.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Arithmetic", "Mental Maths", "Strategic Thinking"],
    players: "2–4 players",
    playTime: "25–45 min",
  },
  {
    id: "product-005",
    name: "Story Cubes",
    category: "Language & Creativity",
    imagePath: "images/photo_7_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Roll the illustrated dice and weave the symbols into an imaginative story. Story Cubes spark narrative thinking, expand vocabulary, and turn even the shyest child into a confident storyteller.",
    ageMin: 5,
    ageLabel: "Ages 5+",
    badge: "popular",
    inStock: true,
    skills: ["Storytelling", "Vocabulary", "Creative Thinking"],
    players: "1–6 players",
    playTime: "10–30 min",
  },
  {
    id: "product-006",
    name: "Science Lab Kit",
    category: "Science & Discovery",
    imagePath: "images/photo_8_2026-03-21_16-00-02.jpg",
    priceUSD: 3.39,
    priceEGP: 180,
    description: "A hands-on experiment kit packed with safe, child-friendly materials for 12 mini science activities — from volcanic reactions to simple circuits. Curiosity guaranteed.",
    ageMin: 7,
    ageLabel: "Ages 7+",
    badge: null,
    inStock: true,
    skills: ["Scientific Method", "Observation", "Critical Thinking"],
    players: "1–3 players",
    playTime: "30–60 min",
  },
  {
    id: "product-007",
    name: "Balance & Build",
    category: "Motor Skills",
    imagePath: "images/photo_9_2026-03-21_16-00-02.jpg",
    priceUSD: 1.70,
    priceEGP: 90,
    description: "Wooden blocks in unexpected shapes that children must balance and stack as high as possible without toppling. Trains fine motor control, patience, and basic physics intuition.",
    ageMin: 3,
    ageLabel: "Ages 3+",
    badge: null,
    inStock: true,
    skills: ["Fine Motor Control", "Balance", "Physics Intuition"],
    players: "1–4 players",
    playTime: "15–25 min",
  },
  {
    id: "product-008",
    name: "World Explorer Map",
    category: "Geography & Culture",
    imagePath: "images/photo_10_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "A giant illustrated floor map paired with trivia cards covering every continent. Children place landmark tokens, answer geography questions, and discover fascinating facts about world cultures together.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Cultural Awareness", "Trivia & Memory"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-009",
    name: "World Explorer Map 2",
    category: "Geography & Culture",
    imagePath: "images/photo_11_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "An expanded edition of World Explorer featuring Asia and the Middle East in vivid detail, with 80 new trivia cards and illustrated animal tokens for each region.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Cultural Awareness", "Trivia & Memory"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-010",
    name: "World Explorer Map 3",
    category: "Geography & Culture",
    imagePath: "images/photo_12_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Dive into the Americas — North, Central, and South — through this vibrant map game. Includes cultural trivia, natural wonders cards, and a 3D landmark building challenge.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Cultural Awareness", "3D Building"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-011",
    name: "World Explorer Map 4",
    category: "Geography & Culture",
    imagePath: "images/photo_13_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Europe edition: discover iconic landmarks, languages, and traditions across 44 countries. Includes a bonus 'capitals challenge' card deck for older players.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Languages", "Memory"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-012",
    name: "World Explorer Map 5",
    category: "Geography & Culture",
    imagePath: "images/photo_14_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Africa edition: a beautifully illustrated map celebrating the continent's extraordinary biodiversity, ancient civilisations, and modern cultural achievements.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "History", "Cultural Appreciation"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-013",
    name: "World Explorer Map 6",
    category: "Geography & Culture",
    imagePath: "images/photo_15_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Oceania & Antarctica edition — the most unusual and fascinating edition yet. Explore the outback, coral reefs, polar ice, and indigenous cultures through rich illustrations and discovery cards.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Nature Science", "Cultural Awareness"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-014",
    name: "World Explorer Map 7",
    category: "Geography & Culture",
    imagePath: "images/photo_16_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "The complete world atlas game — all six map editions combined into one mega set with over 200 trivia cards and a collaborative mode where teams race to fill in the world together.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Teamwork", "Strategic Planning"],
    players: "2–8 players",
    playTime: "45–90 min",
  },
  {
    id: "product-015",
    name: "World Explorer Map 8",
    category: "Geography & Culture",
    imagePath: "images/photo_17_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "A travel-size compact edition designed for holidays and long journeys. Folds into a portable carry case and plays in as little as 15 minutes.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Quick Thinking", "Memory"],
    players: "2–4 players",
    playTime: "15–30 min",
  },
  {
    id: "product-016",
    name: "Explorer Map Plus",
    category: "Geography & Culture",
    imagePath: "images/photo_18_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "An enhanced edition with augmented reality tiles — point the companion app at any token to unlock a short animated story about that country's history and wildlife.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Digital Literacy", "History"],
    players: "1–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-017",
    name: "Explorer Night Edition",
    category: "Geography & Culture",
    imagePath: "images/photo_19_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "A glow-in-the-dark astronomy and geography mashup. Children identify constellations and their countries of origin in a fun bedtime-friendly format.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Astronomy", "Geography", "Pattern Recognition"],
    players: "1–4 players",
    playTime: "20–40 min",
  },
  {
    id: "product-018",
    name: "Explorer Sea Voyage",
    category: "Geography & Culture",
    imagePath: "images/photo_20_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Navigate the world's oceans by sail in this strategic route-building game. Learn ocean names, currents, and famous explorers' journeys as you plot your course.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Route Planning", "History"],
    players: "2–5 players",
    playTime: "30–50 min",
  },
  {
    id: "product-019",
    name: "Explorer Culture Quiz",
    category: "Geography & Culture",
    imagePath: "images/photo_21_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "200 illustrated culture and geography question cards spanning food, music, art, sport, and nature from every corner of the globe. Playable as a standalone game or combined with any Explorer Map edition.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["General Knowledge", "Cultural Awareness", "Quick Recall"],
    players: "2–8 players",
    playTime: "20–40 min",
  },
  {
    id: "product-020",
    name: "Explorer Map Deluxe",
    category: "Geography & Culture",
    imagePath: "images/photo_22_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Premium wooden token edition of World Explorer Map. Every piece is crafted from sustainably sourced wood with hand-painted finishes — a keepsake as much as a game.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Cultural Awareness", "Tactile Learning"],
    players: "2–6 players",
    playTime: "30–60 min",
  },
  {
    id: "product-021",
    name: "Explorer Map Jumbo",
    category: "Geography & Culture",
    imagePath: "images/photo_23_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "A classroom-sized floor map measuring 120 × 90 cm, ideal for schools and play centres. Robust wipe-clean surface, 300 cards, and a teacher's activity guide included.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Group Learning", "Collaboration"],
    players: "4–20 players",
    playTime: "45–90 min",
  },
  {
    id: "product-022",
    name: "Explorer Map Mini",
    category: "Geography & Culture",
    imagePath: "images/photo_24_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "Pocket-sized geography flash-card game for two players. Perfect for waiting rooms, car trips, or a quick five-minute challenge anywhere.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Geography", "Quick Thinking", "Competitive Play"],
    players: "2 players",
    playTime: "5–15 min",
  },
  {
    id: "product-023",
    name: "Explorer Map Masterclass",
    category: "Geography & Culture",
    imagePath: "images/photo_25_2026-03-21_16-00-02.jpg",
    priceUSD: null,
    priceEGP: 150,
    description: "The ultimate geography challenge for advanced young learners. Features a detailed political map, capital cities quiz, flags deck, and a strategic territory-building board game — all in one box.",
    ageMin: 6,
    ageLabel: "Ages 6+",
    badge: "new",
    inStock: true,
    skills: ["Advanced Geography", "Flags & Capitals", "Strategic Thinking"],
    players: "2–6 players",
    playTime: "45–75 min",
  },
];

// ─── Export (accessed by app.js) ──────────────────────────────
// No module system needed — these are global variables loaded via <script>
